/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    //public String getGreeting() {
     //   return "Hello world.";
    //}

    public static void main(String[] args) {
      //  System.out.println(new App().getGreeting());
        Vehicle carA = new Vehicle("car1","Audi");
        Vehicle carB = new Vehicle("car2","Toyota");
        Car carC = new Car("car3","Honda");
        carA.speedup(50);
        carB.speedup(40);
        carC.speedup(180);
        carC.speedup(280);
    }
}

class Car extends Vehicle{
    public Car(String name,String brand){
        super(name, brand);
    }

    @Override
    public void speedup(int speed){
        if (speed <= 200){
            super.speedup(speed);
        }
        else
            System.out.println("Speed Up Failed!!");
    }
}
class Vehicle{
    private String name;
    private String brand;

    public Vehicle(String name,String brand){
        this.name =name;
        this.brand = brand;
    }

    public void speedup(int speed){
        System.out.println("Name :" + this.name + " Brand :" + this.brand + " speedup to " + speed + "km");
    }
}
